### ISSUE TITLE
Is there a way to speed up mod loading?

### ISSUE THREAD

**Issue by linonetwo** [SamboyCoding/RimworldBetterLoading#1]
Is there a hook that can take control of the mod loading?
If there is, I can make it multithreaded.

**Comment by SamboyCoding** [comment]
I don't have a hook for it, though there probably IS one that can be done, but messing with the mod loading is perhaps not a good idea. I did consider it, though.

**Comment by linonetwo** [comment]
Okay, maybe just waiting for

**Comment by SamboyCoding** [comment]
No, i'll reopen this, as it's interesting. I'll see if I can get it working :)

**Comment by linonetwo** [comment]
I'm currently using [rimthemes](https://steamcommunity.com/sharedfiles/filedetails/?id=1668983184&tscn=1551472315) to get loading progress info, since your mod is not uploaded to steam workshop currently.

And I found the most time-consuming step is "parsing default values", but I'm not sure. If your mod has a statistic analyze report, it will be more clear which part is the most important part to optimize.

Tynan [said he will optimize it in the future](https://twitter.com/TynanSylvester/status/1082378656008294400), but I don't know when.

**Comment by SamboyCoding** [comment]
You do know you can install non workshop mods on the steam version of the game, right?

**Comment by orbittwz** [comment]
Is this relevant now? maybe to be closed?

**Comment by linonetwo** [comment]
Yes, glad that we have a mod in the workshop that can speed up mod loading, and later Tynan integrate that mod into the core!
