### ISSUE TITLE
Support for Fluffys mod-manager?

### ISSUE THREAD

**Issue by emipa606** [SamboyCoding/RimworldBetterLoading#2]
It would be nice to add support for fluffys mod-manager.
https://github.com/FluffierThanThou/ModManager/blob/master/ForModders.md
That way you can get a notification when new releases comes out.

**Comment by SamboyCoding** [comment]
Yep, it's on my todo list, thanks for raising an issue. I need to do this too because mod manager complains about loading BL above core. 

Also, it would be quite nice if github could actually let me know when someone raises an issue...

**Comment by emipa606** [comment]
Heres something to start from if you want
[Manifest.xml.txt](https://github.com/SamboyCoding/RimworldBetterLoading/files/3017303/Manifest.xml.txt)

**Comment by SamboyCoding** [comment]
Implemented in v2, at long last.
