### ISSUE TITLE
"You can only patch implemented methods/constructors" error

### ISSUE THREAD

**Issue by alextd** [SamboyCoding/RimworldBetterLoading#3]
Problem on these lines: https://github.com/SamboyCoding/RimworldBetterLoading/blob/1293f7761fec51f3aeb9bc7d070014fae7496d24/Source/Compat/HugsLib/StageHugsLibInit.cs#L120

This assumes other mods defined Initialize and DefsLoaded. If they don't, there will be this harmony error (e.g. with SimpleSidearms):

`You can only patch implemented methods/constructors. Path the declared method HugsLib.ModBase.Initialize() instead."

BetterLoading should check before patching here, and make sure the DeclaredType for the method is actually childMod's type and not ModBase.

**Comment by SamboyCoding** [comment]
Fixed in release 2.3.0.0, thanks for the report!
